### ISSUE TITLE
Why does epaxos need `seq`?

### ISSUE THREAD

**Issue by drmingdrmer** [efficient/epaxos#12]
Hi guys:

In the epaxos paper it says:
`seq` is only used to **break dependency cycles**,
when there is a group of **strongly connected components**.

My question is:
 
Because the committed commands graphs are identical on all replicas,
if every replica could determine the command order in the same way, but without the help of `seq`, the state machines are still consistent.

And Because **strongly connected components** are formed only when interfering commands are processed simultaneously(one command starts while another command is in progress), any order is reasonable to clients.

Thus it is not necessary to have `seq` in epaxos.

Please let me know if I missed anything that relies on `seq` or whether there is some other consideration to keep `seq`.

Thanks a lot 😆

**Comment by imoraru** [comment]
Strongly connected components can unfortunately include commands that do not overlap in time. Say A commits before B. They can still be part of the same SCC if there exists C that overlaps both A and B, and A <-> C <->B.

Having said that, it is good to get rid of `seq` and all the implementation corner cases it causes. The easiest way to do this: ACK commands as committed to the client only after their dependency graph has been finalized and can no longer grow (i.e., all the commands in the dependency graph of the current command have been committed before we tell the client that the current command has been committed). Notice how this makes the example in the previous paragraph impossible.

Another way to get rid of `seq` is to replace it with something easier to compute. For example, if the replicas have precisely synchronized clocks, seq could be the timestamp taken at the command leader when the command arrives from the client.

**Comment by drmingdrmer** [comment]
Well, it is the A-C-B case that I missed. Thanks.

I think the point is what a client expect an ACK means.

An ACK should indicate **executed** but not only **committed**. In epaxos "committed" does not imply action taking effect but "executed" does.
It is also weird for a client that an ACK is received but the result of the command may not be seen.
Similar to a HTTP-PUT request, if a client received 200-OK, it means "the content has been stored and can be seen by others", but not "the content will be stored in future".

If an ACK indicates "executed" then we can remove `seq` safely, right?

One of the reasons I like epaxos more than other consensus theory is that it totally discards timestamp-based concept.
Because to get an accurate timestamp involves more detail to consider, such as preventing wall clock rolling back.
Introducing another sub-system to provide synchronized time also brings in more availability issues to take care.

**Comment by imoraru** [comment]
> An ACK should indicate executed but not only committed. In epaxos "committed" does not imply action taking effect but "executed" does.
> It is also weird for a client that an ACK is received but the result of the command may not be seen.
> Similar to a HTTP-PUT request, if a client received 200-OK, it means "the content has been stored and can be seen by others", but not "the content will be stored in future".
> 

Hmm, not exactly. It depends on what your commands do, but in general, the client should not care about the distinction between _committed_ and _executed_. Here's an example. Say I am trying to commit command "a := 1". After the system returns _ACK_, all the client should care about is that the next time they do "read a" they get 1; or that if they do "a++; read a" they get 2, etc. In other words, the system doesn't have to execute the command eagerly. It just has to guarantee that it will definitely execute the command in the proper order when the command's effects must be observed. Because in practice we will not need the value of "a" immediately after we have modified it, this gives us the ability to hide some latency from the client.

> If an ACK indicates "executed" then we can remove seq safely, right?

Yes.

> One of the reasons I like epaxos more than other consensus theory is that it totally discards timestamp-based concept.
> Because to get an accurate timestamp involves more detail to consider, such as preventing wall clock rolling back.
> Introducing another sub-system to provide synchronized time also brings in more availability issues to take care.

Yes, that's fair. Sometimes these time services are readily available. If not, they can be a pain to engineer.

**Comment by drmingdrmer** [comment]
> Hmm, not exactly. It depends on what your commands do, but in general, the client should not care about the distinction between committed and executed. Here's an example. Say I am trying to commit command "a := 1". After the system returns ACK, all the client should care about is that the next time they do "read a" they get 1; or that if they do "a++; read a" they get 2, etc. In other words, the system doesn't have to execute the command eagerly. It just has to guarantee that it will definitely execute the command in the proper order when the command's effects must be observed. Because in practice we will not need the value of "a" immediately after we have modified it, this gives us the ability to hide some latency from the client.

You are right. In the "A<->C<->B" scenario, A, C, B probably has `seq` 2,2,3 thus `seq` defines execution order so that B execute after A.
