### ISSUE TITLE
question about the proof of Lemma 2. The recovery procedure for Thrifty Egalitarian Paxos can always make progress (as long as the system is live)

### ISSUE THREAD

**Issue by lishulong** [efficient/epaxos#17]
Hi,
firstly，thanks a lot for your great work on epaxos and sharing it.

I get a question about the proof part of  Lemma 2(The recovery procedure for Thrifty Egalitarian Paxos can always make progress (as long as the system is live)) in the paper of "A Proof of Correctness for Egalitarian Paxos". 

It's at the bottom on page 16.
![image](https://user-images.githubusercontent.com/13903162/71463128-5fbbd100-27f0-11ea-9e17-9b9b21bc54fc.png)

why is it F + ⌊(F+1)/2⌋?  I mean 
![image](https://user-images.githubusercontent.com/13903162/71463227-a7daf380-27f0-11ea-9617-7f3c5c20acce.png)

**Comment by imoraru** [comment]
F + floor(F/2 + 1/2) == F + ceil(F/2) is the smallest subset (out of the total 2F +1 replicas) with the property that if we commit a command on the fast path after this many pre-accepts, we can still deduce that this command should have committed following any F failures. If this set is any smaller, then we run into the possibility that we could encounter two conflicting commands C1 and C2, each with approximately the same number of surviving pre-accepts, and we cannot decide which one should depend on the other.

**Comment by lishulong** [comment]
thank you so much.
